apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ printf "pd-kf-%s" .Release.Name | trunc 24 }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{ printf "kf-%s" .Release.Name  | trunc 24 }}"
spec:
  selector:
    matchLabels:
      component: "{{ printf "kf-%s" .Release.Name  | trunc 24 }}"
  {{- if .Values.MinAvailable}}
  minAvailable: {{.Values.MinAvailable}}
  {{- else}}
  minAvailable: {{sub .Values.Brokers 1}}
  {{- end}}