apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "kf-svc-%s" .Release.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "kf-{{.Release.Name}}"
spec:
  ports:
  - port: {{.Values.ServerPort}}
    name: server
  clusterIP: None
  selector:
    component: "kf-{{.Release.Name}}"
