apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "zk-cl-%s" .Release.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}"
spec:
  ports:
  - port: {{.Values.zookeeper.ClientPort}}
    name: client
  selector:
    component: "{{.Release.Name}}"